logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    virtual-host: /
    host: 192.168.152.130
    port: 5672
    username: itcast
    password: 123321
    listener:
      simple:
        prefetch: 1 # 每次只能预获取一条消息，处理完成才能获取下一个消息
